### ISSUE TITLE
Exception thrown in SimpleITK ImageFileReader_Execute: d:\a\1\sitk-build\itk\modules\thirdparty\gdcm\src\gdcm\source\common\gdcmException.h:74 (): Impossible

### ISSUE THREAD

**Issue by jnumingdeli** [SimpleITK/SimpleITK#1434]
When I read the DICOM file using SimpleITK, the following problem occurred:

Exception thrown in SimpleITK ImageFileReader_Execute: d:\a\1\sitk-build\itk\modules\thirdparty\gdcm\src\gdcm\source\common\gdcmException.h:74 ():
Impossible

The code I use is as follows:
import SimpleITK as sitk
path = 'F:/from_video_to_img/1.dcm'
img = sitk.ReadImage(path)
img_array = sitk.GetArrayFromImage(img)
print(img_array.shape)

Then, I used RadiAntViewer software open this DICOM file, the possibility of dicom file damage is excluded.

Does anyone have a problem with that? How should I solve this problem? Thanks!!!

**Comment by zivy** [comment]
Hello @jnumingdeli,

Be aware that DICOM is a complicated standard with some readers willing to accept/read non compliant files while others are more strict, so a successful read does not mean the file is fine (DICOM compliant / not corrupt). 

That being said, the information in the post is not sufficient for reproducing the problem. Can you share the image? This will help identify the problem and either address it if it is an issue on our side or provide a more informative error message if the issue is with the file.

**Comment by jnumingdeli** [comment]
Thanks, This is the link of the dicom file:
https://1drv.ms/u/s!Am4A2gIbR4A9hH-z8Xuakn5v8Y8A?e=EctEmu

**Comment by jnumingdeli** [comment]
Thank you @zivy 
This is the link of the dicom file:
https://1drv.ms/u/s!Am4A2gIbR4A9hH-z8Xuakn5v8Y8A?e=EctEmu

**Comment by zivy** [comment]
Hello @jnumingdeli,

This appears to be an issue with GDCM, the library used for reading DICOM, ongoing discussion on the [gdcm mailing list](https://sourceforge.net/p/gdcm/mailman/gdcm-developers/?viewmonth=202108).

**Comment by jnumingdeli** [comment]
Thank you @zivy
I feel this may be related to the number of frames of the video. In the same batch of data, when the number of frames is less than 1200, you can open it, and if it is greater than 1200, it will report the same error. 
Hopefully this will help solve the problem. 
If you have any latest news or need any help, please contact me. Thank you very much！

**Comment by zivy** [comment]
Hello @jnumingdeli,

Thanks for confirming that this is indeed the problem identified in the gdcm mailing discussion, overflow. This issue will be closed when resolved in gdcm, so you will be automatically notified.

**Comment by blowekamp** [comment]
This is is contained in the SimpleITK 2.2 RCs

**Comment by blowekamp** [comment]
This fix is in SimpleITK the 2.2.0 release.

**Comment by Marsxpc** [comment]
@zivy@blowekamp hello, i do not think this bug has been fixed, please help me check
This is the link of the dicom file:
https://github.com/Marsxpc/zcsmart/releases/download/dicom_file01/N36HIKO2

**Comment by zivy** [comment]
Hello @Marsxpc,

What version of SimpleITK are you using? I believe this bug was indeed fixed in release 2.2.0. 

I am able to read the color US video you provided using the [latest pre-release](https://github.com/SimpleITK/SimpleITK/releases/tag/latest) which is what I have installed. The bug was likely fixed in the older release, 2.2.0. If that release doesn't work for you, just upgrade to the latest pre-release. 

Note that this is a large image (3.7GB, 1016x708x1733x3bytes), so use a computer that has sufficient RAM.

**Comment by Marsxpc** [comment]
Hello @zivy 
I use the same code and the same image as jnumingdeli , and the version of  SimpleITK is 2.3.0.dev296. It still throws gdcmException 74
my computer's config: RAM 16.0 GB (15.9 GB usable)

**Comment by blowekamp** [comment]
Interesting. For your provided path, it appears you are using windows. We should try to reproduce on that system.

**Comment by zivy** [comment]
@blowekamp, your suspicion is correct. I was able to reproduce the issue (SimpleITK Version: 2.2.1 (ITK 5.3)) on a windows 10 machine with 48GB of RAM, so it isn't likely to be a memory allocation issue. Same SimpleITK release on OSX reads the image without an issue.

**Comment by Marsxpc** [comment]
hello, Is this issue fixed?@zivy

**Comment by zivy** [comment]
Hello @Marsxpc, 
It doesn't appear to be addressed. The issue is at the ITK level, see [this issue](https://github.com/InsightSoftwareConsortium/ITK/issues/2681), which is why it was closed for SimpleITK. I just pinged the relevant person there.
